### PR TITLE
Alpha 9 Update

### PR DESCRIPTION
**Pull request by TehJoE**

### CODE REVIEW

**Comment by noone57** [comment]
Hey, thanks for all of this ! Just merged everything. Happy to create a release when you are.

**Comment by TehJoE** [comment]
I'm pretty content with the the current version being the 0.9.0 release.
Can't have A2B being the only mod holding up someone's Alpha 9 update ;)

Next thing I was planning on working on is getting the teleporter/receiver
pair to release a burst of heat every time they teleport an item,
proportional to distance traveled. It seemed like a pretty neat way to
begin implementing temperature concerns in a way that wasn't just "watch
out or your belts will slowly cook themselves", and more like "sending a
couple steel chunks across the map might instantly fry the dude loading the
teleporter if you don't ventilate the room". Sound like fun?

**Comment by noone57** [comment]
Great. I'll release the update then. 

Good idea on the heat flash. Will be interesting to find a good balance, i.e. duration vs intensity. That will open the door to many things. E.g. I thought that belt freezing in very cold places (e.g. -10C ?) could be interesting too. I'm not quite sure how the temperature works exactly, but assuming each belt item has a "temperature" value associated to it, then we could design neat effects if this goes below/above a certain value. I.e., if too cold, doesn't move, if too hot, gets on fire, etc ... all these could be fixed with extra research. These could be either build hard-core inside the mod (via fixed probabilities), or more elegantly using random events so that the probability of an exploding belt is higher in more difficult settings ...

**Comment by TehJoE** [comment]
Well, from what I've found while fixing the heat-sealing issue, individual
Things themselves don't actually carry a temperature value, but Rooms do.
This leads to all sorts of weirdness, but since the fix allowing the belts
to transfer heat involved making them no longer Impassable (but still
unable to path through, so effectively impassible), we CAN now associate to
a given belt a Room it's in (before it was seen as a barrier between Rooms
and so was never actually in one), which does have a temperature.

 Freezing up in the cold doesn't sound difficult, just a switch to
Phase.Offline under a certain temperature, and if I recall correctly (one
of the bugs in the temperature fix involved the belts spontaneously heating
a room to 4000F), any object with a flammability score will self-ignite at
high enough temperatures without any extra work, so that's basically a core
feature.

Another neat research idea may be thermal efficiency improvements for the
teleporters, to make those heat flashes less severe. That way we can make
them MORE severe by default ;)

A final one that I'm not completely sure about - a chance for a belt to jam
if its HP is not totally full. This way we can implement a random chance
for belts to self-damage (and firefights near the belts can be
problematic), but repair-designated pawns will automatically repair them,
solving the jam. Obviously, a corresponding research opportunity to
minimize/nullify that occurrence. Comments/Concerns on that?

**Comment by noone57** [comment]
Re the chance of a damaged belt getting stuck. I like it. It's realistic and also forces people to pay attention to their belt system, and not just use them as sandbags :-)

I guess it should be random-ish, i.e. a probability of getting stuck increasing with damage, and when stuck, it only works again when fully repaired. To avoid this being too annoying, I suppose I would make the chance of getting stuck at 60% damage, and then increase linearly to 100% at 90% damage, or thereabout. So, the entire chain doesn't break down because of simple wear and tear.

The 'switch to off' below a certain temperature sounds like the way to go. And additional research would then simply decrease that value by e.g. 20C or so, while increasing the electricity consumption of the belt elements by e.g. 25% or so. For the extremely cold maps, we could have 2-tiers: A2B - thermal insulation I and A2B - thermal insulation II

For the heat, the chance of self-ignition sounds good. Should be a reasonably high value though, e.g. 400C or so, I suppose. Otherwise, the entire conveyor chain might catch fire and burn down like a row of matches, if one element catches fire ... 

I guess ultimately we will need to find the right balance between "fun bugs and features" and "unreliable belt systems requiring too much maintenance".

**Pull request merged**
